name: 'Stale Parked Items'
on:
  schedule:
    - cron: '40 20 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3.0.18
        with:
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had any
            activity recently. It will be closed presently if no further activity occurs.
            Thank you for your contribution.
          close-issue-message: >
            This issue has been automatically closed as it has not had any activity recently.
            Thank you for your contribution.
          days-before-stale: 60
          days-before-close: 30
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Stale'
          only-issue-labels: 'Parked'
